version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/app/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - backend-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 